### ISSUE TITLE
extracting OTU tables

### ISSUE THREAD

**Issue by ianpgm** [meringlab/MicrobeAtlasWebsite#1]
Is there a way of extracting an OTU table for a given set of samples? If I have found a set of samples containing an OTU I'm interested in, is there a way I can download all the data in the database for those samples to look at the abundance of all OTUs across all the samples I'm interested in?

Also just a quick note: this is a great tool, I just saw Janko Tackmann's talk at ISME and thought I'd take a look at it. Thanks for developing it!

**Comment by grexor** [comment]
Hi ianpgm,

thank you for your comment! The current interface provides download of the OTU table for all samples displayed on the page (search by keyword etc. narrows the samples down).

Did you have in mind providing a list of sample IDs directly (ERS*, SRS*)? We are currently working on that,

Cheers,
Gregor

**Comment by ianpgm** [comment]
Ah great, I can see that now. What I’d like to do is the following:

1. Put a sequence into MAPseq -> 2. find all samples containing a match for that sequence -> 3. download the OTU table for all those samples

At the moment 1->2 doesn’t seem possible, as the list of samples on the OTU page only (a) shows the 10 most abundant samples and (b) has no OTU table download option like in the main samples view. 2->3 doesn’t seem possible as you can only download the OTU table for up to 200 samples at a time, and if the OTU of interest is in more than 200 samples then you can’t get them all.

Providing a list of sample IDs for where a given OTU is found is a good idea - that way if someone wants to get the run table or fastq files from SRA for those samples then it’s straightforward. What would solve my problem is if there was also an upload sample ID option, so that you could take that list of sample IDs and retrieve samples based on membership of that list. Then all you’d need would be a way of downloading the OTU table for everything retrieved (not just the top 50-200) and this would work.

Another solution would be to allow people to download the OTU table for the entire dataset (maybe just on an ftp site) and sort out the bits they need themselves.

In any case, I’m very grateful that this tool has been developed and these are just some thoughts that are not meant as a criticism of all the good features that the site already has!

**Comment by grexor** [comment]
Thank you Ian,

for now we extended all tables to be paginated and table results can be downloaded. We will shortly add the features you suggest and links to complete datasets. Thank you for your patience and understanding since this is a pre-release of our research / software and we are currently working on several essential features that are coming up shortly,

Cheers,
Gregor

**Comment by ianpgm** [comment]
Thanks very much, it's good to see the download option! However, I seem to be downloading corrupted gzip files (e.g. `gunzip: taxon_samples.tab.gz: unexpected end of file`). Is this a universal problem or is there something I'm doing wrong? Thanks!

**Comment by grexor** [comment]
Dear Ian,

we are sorry for the inconvenience, this issue is resolved in the new release coming end of this month (1 week time), so thank you for your patience and also thank you so much for already using the resource! Will keep you updated shortly,

All the best,
Gregor

**Comment by grexor** [comment]
The download links have now been fixed so closing this issue.
