### ISSUE TITLE
Differing numbers of samples for each taxon?

### ISSUE THREAD

**Issue by ianpgm** [meringlab/MicrobeAtlasWebsite#2]
I'm having trouble interpreting how many samples each taxon is found in.
For example, on this page: http://devel.microbeatlas.org/index.html?action=taxa_detail&taxa_name=B16S;90_10948;96_36159;97_45106
I can see that if you add up the various environment types you get 1500+27+231+120 with their mean abundances in each sample type. However, down where the table of abundances is, it says "samples with abundance, found 66 samples, displaying samples 1-66". How do you get two numbers that are so different (1878 vs. 66), what's the difference between these two numbers?

**Comment by grexor** [comment]
Dear Ian,

the "Samples with Abundances" table for now shows only max 100 samples where the selected taxon is most abundant, however we are also extending this. Expect a new release end of this month (1 week time) and thank you for your patience,

All the best,
Gregor

**Comment by grexor** [comment]
This has now been fixed and all samples are shown, closing this issue.
