### ISSUE TITLE
microbe abundance calculation

### ISSUE THREAD

**Issue by ikher** [meringlab/MicrobeAtlasWebsite#21]
How does the MAP calculate microbe abundances?
I would say that the abundances shown should be relative (e.g. % of reads), but the legend says ppm (parts per million?).
I have gone through the original paper and all the documentation I have found (Github, article Supplemental Information, etc.), but I still do not understand how the MAP obtains these abundances…
Could someone give me a hint abut it?

Thanks!

**Comment by lukasmalfi** [comment]
Hi ikher, 

Thanks for the question.
The microbe abundances are indeed relative! They are obtained by first identifying all small subunit rRNA sequences in a sample, and then dividing the amount of confidently mapped reads of each identified OTU by it to calculate the respective relative abundance . Parts per million (ppm) is just another way of expressing it (easier to read for very low abundances)- 1,000 ppm would for example correspond to 0.1% (parts per hundred).

I hope that helped- if not or there is something that is still unclear, feel free to reach out again.

Best,
Lukas
