### ISSUE TITLE
Ordering of taxon search results

### ISSUE THREAD

**Issue by jtackm** [meringlab/MicrobeAtlasWebsite#4]
Below the representative OTU, taxon search results seem to currently be ordered by OTU ID, which is not very informative. We could perhaps show them ordered by number of samples (descending).

**Comment by jfmrod** [comment]
One more issue is that when searching for Escherichia coli, "francisella" is shown as the first hit, one of the annotated strains in that OTU is indeed marked as Escherichia coli, but in this case to fix the problem just the "representative" species name should be used for the search.

**Comment by grexor** [comment]
Fixed this now, however we may still need to change / alter sorting. For now I added sort by "Number of Samples" which is default. The sort by "Name" is actually the "taxon ID", which probably should be removed.
